language: python
python:
  - 3.8.7
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - pip install -r requirements.txt
script: coverage run -m unittest
after_success:
  - codecov # submit coverage